Repository acmucsd/Space-2019, pull requests merged in 2020-01, with the labels that each got.

#11 Page 2 Web (Closes #6)
  package.json
  public/index.html
  src/assets/astro-greet.svg
  src/components/particle-js/index.tsx
  src/components/particle-js/style.less
  src/components/statistic/index.tsx
  src/components/statistic/style.less
  src/components/typing-text/index.tsx
  src/components/typing-text/style.less
  src/index.tsx
  src/pages/page1/index.tsx
  src/pages/page1/style.less
  src/pages/page2.tsx
  src/pages/page2/index.tsx
  src/pages/page2/style.less
  src/pages/page3.tsx
  src/pages/page3/index.tsx
  src/pages/page3/style.less
  src/pages/page4/index.tsx
  src/pages/page4/style.less
  src/style.less
  src/styles/reset.less
  src/styles/style.less
Labels: enhancement, in progress

#12 Navbar + Landing Page
  public/index.html
  src/assets/arrow.png
  src/assets/astro.svg
  src/assets/menu-icon.svg
  src/assets/mini-rocket-mobile.svg
  src/assets/mini-rocket.svg
  src/assets/title.svg
  src/components/faq/index.tsx
  src/components/faq/style.less
  src/components/navbar/index.tsx
  src/components/navbar/style.less
  src/index.tsx
  src/pages/page1/index.tsx
  src/pages/page1/style.less
  src/pages/page2/index.tsx
  src/pages/page3/index.tsx
  src/pages/page4/index.tsx
  src/styles/style.less
Labels: enhancement

#20 Created Footer (Closes #8)
  src/assets/email.svg
  src/assets/facebook.svg
  src/assets/medium.svg
  src/assets/space.svg
  src/components/particle-js/index.tsx
  src/components/statistic/index.tsx
  src/index.tsx
  src/pages/footer/index.tsx
  src/pages/footer/style.less
  src/pages/page2/index.tsx
  src/pages/page2/style.less
  src/styles/style.less
  yarn.lock
Labels: enhancement, good to merge

#30 Button styling reflects figma
  src/components/button/index.tsx
  src/components/button/style.less
  src/components/faq/index.tsx
  src/components/faq/panel.tsx
  src/components/faq/style.less
  src/components/navbar/index.tsx
  src/pages/page1/style.less
  src/styles/style.less
Labels: good to merge

#31 New Way to Update Stats
  package-lock.json
  src/pages/page2/index.tsx
  src/pages/page2/stats.json
Labels: enhancement, good to merge

#33 Finished Page 4 and FAQ Component (Closes #4)
  src/components/faq/index.tsx
  src/components/faq/panel.tsx
  src/components/faq/style.less
  src/components/navbar/index.tsx
  src/components/tabs/index.tsx
  src/components/tabs/style.less
  src/components/tabs/tab.tsx
  src/index.tsx
  src/pages/footer/index.tsx
  src/pages/page1/style.less
  src/pages/page2/index.tsx
  src/pages/page4/index.tsx
  src/pages/page4/style.less
Labels: good to merge

#34 Updated FAQ / Moved to JSON File
  src/components/faq/index.tsx
  src/pages/page4/faq.json
  src/pages/page4/index.tsx
Labels: bug, needs review

#38 Added eventzilla link
  src/components/button/index.tsx
  src/pages/page1/index.tsx
  src/pages/page4/faq.json
Labels: good to merge, in progress

#40 Button rewsponsiveness
  src/components/button/style.less
  src/pages/page1/style.less
Labels: needs review

#44 Hecc Yeah Particle.js is Back
  src/components/button/style.less
  src/components/faq/style.less
  src/components/navbar/index.tsx
  src/pages/footer/style.less
  src/pages/page2/style.less
  src/pages/page4/style.less
  src/styles/style.less
Labels: good to merge
